---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
  labels:
    istio-injection: enabled

---

kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: oauth-credentials
  namespace: hello-world
  labels:
    app.kubernetes.io/name: hello-world
    dept: devops
    app: hello-world
  creationTimestamp: null
spec:
  encryptedData:
    client-id: AgB6y7b7snqPab8vWfqgh0GyO+iEaap0PZCEx/By/cCrqEj4ffZ+U9NnkOL4cy4NVbdUZP43uNYpboMfxJ7tKbV++nQU+Qjy+gmq3i6PUI/oMKtjeZORqimlgKZNhYtUbZOwsys27HDplvuuWCVY14Ig4BKG4j3IJSLhLOpqiGdheibf3H8ujE6iC1T6MMALXgFNziIfp7miZOq1on2jq1bvK6+JlPDBXgqVYBJIVYIisrDE8FqurvzZu8VFZQW8WzFcv3EFxjUYpDeySN5Ic6pTTnk1kOpPy3UAYPn5tCZ4i0OTts00I13O/WtHqAAlmhE/rfSRG6QkCGr75ovTVM0YnZq2HS0ZTBOFIZpY7CUPwvwIgod0Gv7UuU+g9+V4m9eIPDLRz99n1/mLEWy+XCSn9lQXKfLO0wGt3Zj8KDlhFk639UqrtaIwg3ke8qecH1L1jCutASKG0j658rD2LADOW7/ukyWVx8CmOK279IkuE4GJpE9f5Y2eln6q6FJdvinrkcTrac5/SUd9JLKjKlDtBydQWE5JUIyjX8H3lBRzBVH6IrSTV2OjzSCrK0LVHLKtnrwkRBTcxR6+jPcoLNRFa7Ht2rI8iy/eBqGtnNo2qtgXG/o1+Hv2qtF1WTaaUWrdtxpT55nv2PJzxBOHMsCNTXmgk7DaGERNiEepGNpoeIT9xHCGww6A/oKzNrl3PfDST0AJcVNzD1zCHHdSwxjtRf1l9Q==
    client-secret: AgBOam1RS2criZmx+zABmbT2XMtIdQ6xb1Hus/axz2n/kfRiZ51OnIAXjJichX/OeywuuU517Q/HSZhsSMqW8Kd4TNNDB0SNMkDmf0YEmQQlLdC9T0T05OUFLSkl2xehgqPouJH7w5r4koohT8rRJZfaZsMeKdhGKBAioqQk8oGQdRmPG8Z51CqhxmurXaIMGbid4wUsQQ/Q+RCKal+Zq+2TBfPvBh43KmOLnGVYQV4BrHNhPaKoqdJXidg3wvYDPjNL+MoRyp6s5KwbaUyvGD6qXI4UAdiDSPSCOX1VEq/KSUWon4Brqtt6qDi8t+JzRQiDs3ijgR15aHvzRtGzz3KXQcxgP9zm0o4w/TWLPybi4Ud1T9SGcIfGoCjYF27B4pBbRe9UyW5DnHswn8Bloc7fRbI+O1AotmVqZa/6Srx5Km40/rs0bhUGlE9s6agXP12pSK7ktpDJ9iZp0NkW9UluZCf0Ecag48YZ5kKV3ZYn6lZNqrEmIzNlzPI0+igd64b6crXjosfO3JizpEawhh/Fjww3+1a3dhbR6b0L4jNHH5hbyTDE6seA5g7Bv7tybemIQfh8OcGou1Ety5VDW7nAvB8/wKp1P6MO1g7X/v/m3dN3ECNkwLhj2wgz4jxiNcQweUExmQxM5fqdWn5CaiEwfYafXKKKNHPVY2x5iqYzvp8Ku6426WEPufjjsjCsdZQGt0mb/E8346tYLKT8JMDHO4L1sdoQOiNH4DomKaLFLKPEYviyzevw
    cookie-secret: AgA7lcnwSXUjOWVWP+8XML7QQIXGVt7TymbqOZ70sdfDSbMzfB/EefZlzJiVpwUJXU+/jvExgciPW/mkzTl7aAH2vTIJXTMdYLJ3tAtJiJdr44XRl6dT9LANcpo6b3Uy2lZY0bajBsc49lYYBnSJGPvu/LLtZu31EBhZheSaZF9iE3Ys31TVDWWq0B6f+dDDaftkTgaDphY4pc1MqRCsfgaNaxf6XbAeq7L5kgyPaYCWxIJpGDdaB6EbUWHXyBkULur/t4WOB3wGWqORait5L5T7v/U3KzLLmXoae5t67sjCju54fhHyPcOpq32xfnyq3pV4znZxcsCDfGwgBsQOqwmsnT9cYq6L1m0KzHA5L3xMF0becaU8+T5rr0lEp7E2ETIaqIgj6ySsedvuu3j4JiwTviZTYF8lAtFuq7wNS3903mlEk57IJrhn5O/vZq8LKZ3gFEORtu4Jdvqy7t4Q4zJ5VDd9b1yPUBxc2rPS1E2QbTZXNseycbJXT+1vPoJpWxhezFjO9NwoKalvOY2mi8MDpN9GWVgMbN+x/LmRGwW4WLEvljTxolz+RyDMtQAh0vctJEqkg7/UU0WBgxdkfp/C29Hj97v4ZL2qbfEulXNQK+EBlryMULPGcDDceqY+0N1H3R3+XVtSIdoj9oTxkh3tRqVPOf75blYfWqueVWNVwqWdOL2k412728pETBH+Kr5bS6RR85jDXCqXAQH56WxDPXg2NxlDAk/kge5eYEkaI2gl46Q=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world
  labels:
    app: hello-world
    app.kubernetes.io/name: hello-world
    dept: devops
    app: hello-world

spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        app.kubernetes.io/name: hello-world
        dept: devops
        app: hello-world

    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/pusher/oauth2_proxy:v3.2.0
        resources:
          requests:
            cpu: 100m

        args:
         - --http-address=0.0.0.0:4180
         - --provider=github
         - --email-domain=*
         - --github-org=dcherman-test-organization
         - --upstream=http://127.0.0.1:8000/

        ports:
        - containerPort: 4180

        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name:  oauth-credentials
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth-credentials
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name:  oauth-credentials
              key: cookie-secret

      - name: hello-world
        image: exiges/nodejs-hello-world:1.0.1
        resources:
          requests:
            cpu: 250m
        readinessProbe:
          httpGet:
            path: /ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /live
            port: 9000
          initialDelaySeconds: 10
          # Allow sufficient amount of time (180 seconds = periodSeconds * failureThreshold)
          # for the registered shutdown handlers to run to completion.
          periodSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        ports:
        - containerPort: 8000
        - containerPort: 9000

---

# apiVersion: v1
# kind: Service
# metadata:
#  name: hello-world
#  namespace: hello-world
#  labels:
#    app.kubernetes.io/name: hello-world
#    dept: devops
#    app: hello-world
# spec:
#  ports:
#  - port: 80
#    targetPort: 4180
#    name: http
#  selector:
#    app: hello-world
#  type: ClusterIP
